baseURL: "https://blog.shangao.tech/"
languageCode: zh-cn
defaultContentLanguage: zh
title: "Blog"
theme: mini
taxonomies:
  category: categories
  tag: tags
params:
  imageBaseUrl: "https://img.shangao.tech"